cs412/urls.py
# file: mini_insta/admin.py
# author: Ashtosh Bhandari ashtosh@bu.edu
# description: main navigation, navigates to corresponding applications
"""
URL configuration for cs412 project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quotes/', include(('quotes.urls', 'quote'), namespace='quotes')),
    path('restaurant/', include('restaurant.urls')),
    path('mini_insta/', include('mini_insta.urls')),
    path('voter_analytics/', include('voter_analytics.urls')),
    path('dadjokes/', include(('dadjokes.urls'))),
    path('project/', include('project.urls'))
] 

urlpatterns += static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.urls import path
from django.conf import settings
from . import views

# URL patterns sepcific to the quotes app
urlpatterns = [
    path (r'', views.main_page), #path to main page(quotes page)
    path (r'quote', views.main_page, name='quote_page'), #path to quote page 
    path (r'show_all/', views.show_all, name='show_all'), #path to show_all page
    path (r'about/', views.about, name = 'about')  #path to the about page 
]

quotes/templates/quotes/about.html
<!-- quotes/templates/quotes/about.html-->

{% extends 'quotes/base.html' %}
    {% block content %}
            
        <div class="about-page">
            <div class="about-box">
                <p>
                   <h1> Welcome to Quotes By Steve Irwin! </h1>
                <br>
                
                This website is a tribute to Steve Irwin's incredible life and lasting impact. He wasn't just a TV star - he was a passionate conservationist who taught the world to respect and protect wildlife. 
                Steve's message of love for animals, nature, and education continues to inspire people of all ages. 
                By sharing his quotes, photos, and legacy, this site aims to keep his mission alive and honor the way he made learning about the natural world exciting, fun, and meaningful.
                <br>
                </p>
            </div>

            <div class="about-box">
            <br>
                <h2> The Crocodile Hunter, Conservationist, and Wildlife Warrior </h2>
                <br>

                Steve Irwin was a world-famous Australian wildlife expert, television personality, and conservationist, best known for his energetic personality and deep love for animals. Born on February 22, 1962, in Essendon, Victoria, Australia, Steve spent his life working to protect wildlife and teach others about the importance of conservation.

                He rose to international fame through his hit TV series, The Crocodile Hunter, where he fearlessly interacted with crocodiles, snakes, and other animals — all while educating viewers in his signature enthusiastic style. His catchphrase “Crikey!” became known around the world and reflected his boundless excitement and passion for nature.

                Steve grew up around animals at the Australia Zoo, which his parents founded. He later took over the zoo and expanded it into a leading conservation and education center. Steve’s mission was simple: to make people fall in love with wildlife — because he believed that “people want to save what they love.”

                Tragically, Steve passed away on September 4, 2006, after a stingray accident while filming in the Great Barrier Reef. His death shocked the world, but his legacy lives on through the work of his family and the Wildlife Warriors foundation, which continues to protect endangered animals and habitats around the globe.

                Today, Steve Irwin is remembered not just as “The Crocodile Hunter,” but as a passionate and fearless ambassador for the planet.
                </p>
            </div>
        </div>
    {% endblock %}

quotes/templates/quotes/base.html
<!-- quotes/templates/base.html-->

{% load static%}
<html>
    <head>
        <title> Quotes By Steve Irwin</title>
        <link rel="stylesheet" href="{% static 'quotes/style.css'%}">
    </head>

    <body>
        <nav>
            <li> <a href = "{% url 'quote:quote_page' %}">Quotes</a></li>
            <li> <a href = "{% url 'quote:show_all' %}">Show all</a></li>
            <li> <a href = "{% url 'quote:about' %}">About us</a></li>

        </nav>
        <!-- page specific contenet here-->
         {% block content %}
         {% endblock %}
    </body>
</html>

quotes/templates/quotes/quotes.html
<!-- quotes/templates/quotes.html-->

{% extends 'quotes/base.html' %}
    {% block content %}

        <div class="quote-page">
            <h1>Steve Irwin Image and Quote</h1>

            <img src={{photo}} width="500" height="500"/>
            
            <div class="quote-box">
                <p>
                     "{{quote}}"
                </p>
            </div>
        </div>
    {% endblock %}

quotes/templates/quotes/show_all.html
{% extends 'quotes/base.html' %}
    {% block content %}
        <div class="show-all-page">

            <h1>Steve Irwin</h1>
        
                <h3> Images of Steve Irwin</h3>

                <div class="image-grid img">
                    {% for img in images %}
                        <img src={{img}} />
                    
                    {% endfor %}
                </div>

            
            
                <h3> Quotes by Steve Irwin</h3>
                <div class="quote-grid">
                    {% for quote in quotes %}
                        <div class="quote-box">
                            <p>"{{quote}}"</p>
                        </div>
                       
                    {% endfor %}
                </div>

            

        </div>    
    {% endblock %}